# Generated by Django 4.2.5 on 2023-11-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConectaPucApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='autor',
            field=models.TextField(max_length=200),
        ),
    ]
